var lang = new Array();

lang['V']                    = 'de';
lang['HINTS']                = 'suchmaschinen-tipps';
lang['ERROR']                = '<p>SEORCH has an error.<br />Please mail me!</p>';
lang['ERRORRANKS']           = '<p class="center">Wegen der sehr hohen Anzahl an Rankingabfragen die aktuell durchgeführt werden<br />können wir nicht jede Anfrage beantworten.<br />Probiere es bitte später wieder oder nutze den kostenpflichtigen <a href="../keywordmonitor">Keywordmonitor</a>.</p>';
lang['ENTER_URL']            = 'Bitte eine URL eingeben!';
lang['ENTER_KEYWORD']        = 'Bitte ein Keyword eingeben!';
lang['DUR_180']              = '<p class="center">Das kann jetzt bis zu 3 Minuten dauern!</p>';
lang['DUR_60']               = '<p class="center">Das kann jetzt bis zu 60 Sekunden dauern!</p><br />';
lang['DUR_30']               = '<p class="center">Das kann jetzt bis zu 30 Sekunden dauern!</p>';
lang['BABYCRAWL_DUR']        = '<p class="center">Das kann jetzt bis zu 3 Minuten dauern.<br/>Die Anzahl der analysierten Seiten hängt von der Antwortzeit deines Servers ab.</p>';
lang['BABYCRAWL_ERROR']      = '<p>Apache Timeout.<br/>Please try again with less sites to crawl or crawl without dynamic parameters (checkbox).</p>';
lang['BIGCRAWL_ENTER']       = 'Bitte eine URL und eine Emailadresse eingeben!';
lang['COMPARISON_ENTER']     = 'Bitte ein Keyword eingeben!';
lang['SSM_SITENAME']         = 'OnPage SEO Tool - Search Engine Optimization - Seorch';
lang['SSM_DESC']             = 'SEO - onpage optimization - How good is a website optimized for search engines? Check the onpage factors and improve your website.';
lang['GOOGLE_100']           = 'Google Top 100 für: ';
lang['GOOGLE_SUGGEST']       = 'Google Suggest Daten für: ';
lang['GOOGLE_SUGGEST_EMPTY'] = 'Keine Ergebnisse';
lang['BING_SUGGEST']         = 'Bing Suggest Daten für: ';
lang['YANDEX_SUGGEST']       = 'Yandex Suggest Daten für: ';
lang['AMAZON_SUGGEST']       = 'Amazon Suggest Daten für: ';
lang['YOUTUBE_SUGGEST']      = 'YouTube Suggest Daten für: ';
lang['COMPARE_MIN_MAX']      = 'Vergleiche mindestens 2 Seiten und maximal 10.';
lang['QUESTIONS_FOR']        = 'Google Suggest Fragen für';
lang['WORKING']              = 'Überprüfe: ';
lang['WORKING2']             = 'Überprüfe: ';
lang['QUESTIONS']            = 'SEORCH / W-Fragen';
lang['ULTRASUGGEST']         = 'SEORCH / Ultrasuggest';
lang['SSM_TOOMUCH']          = 'zuviel';
lang['SSM_LEFT']             = 'übrig';
lang['SSM_ZTOOMUCH']         = 'Zeichen zuviel';
lang['SSM_ZLEFT']            = 'Zeichen übrig';
